# Generated by Django 4.0.6 on 2022-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email_id', models.CharField(max_length=100)),
                ('user_password', models.TextField(max_length=256)),
            ],
        ),
    ]
