# Generated by Django 4.0.6 on 2022-07-17 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_blog_post',
            fields=[
                ('blog_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=256)),
                ('post_content', models.CharField(max_length=1200)),
                ('last_modified_date', models.DateField()),
                ('likes', models.IntegerField()),
                ('user_email_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.tbl_user')),
            ],
        ),
    ]
