# Generated by Django 4.0.6 on 2022-07-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_tbl_blog_post_user_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_blog_post',
            old_name='user_email_id',
            new_name='post_user_email_id',
        ),
    ]
