# Generated by Django 4.0.6 on 2022-07-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0007_alter_tbl_blog_post_post_user_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_blog_post',
            name='post_user_email_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tbl_user'),
        ),
    ]
